Repository api-ghost/api-ghost-ui, pull requests merged in 2025-05, with the labels that each got.

#16 feat(dashboard): Add Toggle Functionality and Component Separation for Dashboard Table
  src/components/LightIndicator.module.scss
  src/components/LightIndicator.tsx
  src/pages/dashboard/Dashboard.tsx
  src/pages/dashboard/__mocks__/mockHistoryList.ts
  src/pages/dashboard/table-area/DetailRow.tsx
  src/pages/dashboard/table-area/TableArea.module.scss
  src/pages/dashboard/table-area/TableArea.tsx
  src/pages/dashboard/table-area/TableRow.tsx
Labels: enhancement, 0.0.1-BETA

#20 chore(folder): restructure component and style directories
  .gitignore
  src/common/components/LightIndicator.module.scss
  src/common/components/LightIndicator.tsx
  src/common/side-bar/Sidebar.module.scss
  src/common/side-bar/Sidebar.tsx
  src/common/sidebar/Sidebar.tsx
  src/common/types/HistoryItem.ts
  src/common/types/HttpMethod.ts
  src/common/types/NodeEndPoint.ts
  src/common/types/TabItem.ts
  src/common/types/index.ts
  src/pages/dashboard/Dashboard.tsx
  src/pages/dashboard/__mocks__/mockHistoryList.ts
  src/pages/dashboard/components/flow-graph-area/FlowGraphArea.tsx
  src/pages/dashboard/components/header-tabs/HeaderTabs.tsx
  src/pages/dashboard/components/latency-graph-area/LatencyGrahpArea.tsx
  src/pages/dashboard/components/latency-graph-area/LatencyGraph.tsx
  src/pages/dashboard/components/main-content/MainContent.tsx
  src/pages/dashboard/components/table-area/DetailRow.tsx
  src/pages/dashboard/components/table-area/TableArea.tsx
  src/pages/dashboard/components/table-area/TableRow.tsx
  src/pages/dashboard/controllers/TabsController.ts
  src/pages/dashboard/hooks/useTabsController.ts
  src/pages/dashboard/styles/Dashboard.module.scss
  src/pages/dashboard/styles/FlowGraphArea.module.scss
  src/pages/dashboard/styles/HeaderTabs.module.scss
  src/pages/dashboard/styles/LatencyGraph.module.scss
  src/pages/dashboard/styles/LatencyGraphArea.module.scss
  src/pages/dashboard/styles/MainContent.module.scss
  src/pages/dashboard/styles/Sidebar.module.scss
  src/pages/dashboard/styles/TableArea.module.scss
  src/pages/flow-canvas/FlowCanvas.tsx
  src/pages/flow-canvas/__mocks__/mockNodeData.ts
  src/pages/flow-canvas/components/api-list/ApiList.tsx
  src/pages/flow-canvas/components/custom-node/BodyEditor.tsx
  src/pages/flow-canvas/components/custom-node/CustomNode.tsx
  src/pages/flow-canvas/components/scenario-list/ScenarioList.tsx
  src/pages/flow-canvas/hooks/useFlowCanvas.ts
  src/pages/flow-canvas/styles/ApiList.module.scss
  src/pages/flow-canvas/styles/BodyEditor.module.scss
  src/pages/flow-canvas/styles/CustomNode.module.scss
  src/pages/flow-canvas/styles/FlowCanvas.module.scss
  src/pages/flow-canvas/styles/ScenarioList.module.scss
Labels: enhancement, 0.0.1-BETA

#22 chore(dashboard): update import paths to absolute after folder restructure
  src/common/sidebar/Sidebar.module.scss
  src/pages/dashboard/Dashboard.tsx
  src/pages/dashboard/components/flow-graph-area/FlowGraphArea.tsx
  src/pages/dashboard/components/header-tabs/HeaderTabs.tsx
  src/pages/dashboard/components/latency-graph-area/LatencyGrahpArea.tsx
  src/pages/dashboard/components/latency-graph-area/LatencyGraph.tsx
  src/pages/dashboard/components/main-content/MainContent.tsx
  src/pages/dashboard/components/table-area/DetailRow.tsx
  src/pages/dashboard/components/table-area/TableArea.tsx
  src/pages/dashboard/components/table-area/TableRow.tsx
  src/pages/dashboard/styles/ApiRequestNode.module.scss
Labels: 0.0.1-BETA

#24 feat[flow-canvas]: Implement body tab UI with sub tab memory and MVC structure
  src/pages/flow-canvas/components/api-list/ApiList.tsx
  src/pages/flow-canvas/components/custom-node/BodyEditor.tsx
  src/pages/flow-canvas/controllers/BodyEditorTabsController.ts
  src/pages/flow-canvas/hooks/useBodyEditorController.ts
  src/pages/flow-canvas/styles/BodyEditor.module.scss
  src/pages/flow-canvas/styles/CustomNode.module.scss
  src/pages/flow-canvas/styles/FlowCanvas.module.scss
  src/styles/_colors.scss
Labels: enhancement, 0.0.1-BETA, style

#38 feat(flow-canvas): Render mock schemas in BodyEditor tab
  src/common/types/NodeEndPoint.ts
  src/common/types/index.ts
  src/common/utils/schemaUtils.ts
  src/pages/flow-canvas/FlowCanvas.tsx
  src/pages/flow-canvas/__mocks__/mockNodeData.ts
  src/pages/flow-canvas/components/custom-node/BodyEditor.tsx
  src/pages/flow-canvas/components/custom-node/CustomNode.tsx
  src/pages/flow-canvas/components/mapping-modal/MappingModal.tsx
  src/pages/flow-canvas/components/mapping-modal/MappingPanel.tsx
  src/pages/flow-canvas/constants/color.ts
  src/pages/flow-canvas/hooks/useBodyEditor.ts
  src/pages/flow-canvas/hooks/useBodyEditorController.ts
  src/pages/flow-canvas/hooks/useCustomNode.ts
  src/pages/flow-canvas/hooks/useFlowCanvas.ts
  src/pages/flow-canvas/hooks/useMappingModal.ts
  src/pages/flow-canvas/hooks/useMappingSelection.ts
  src/pages/flow-canvas/styles/CustomNode.module.scss
  src/pages/flow-canvas/styles/MappingModal.module.scss
  src/pages/flow-canvas/types/bodyEditorTabs.ts
  src/pages/flow-canvas/types/index.ts
  src/pages/flow-canvas/types/mapping.ts
Labels: enhancement, 0.0.1-BETA

#51 feat(flow-canvas): integrate mock endpoints using updated type definition
  src/common/service/api.ts
  src/common/types/HttpMethod.ts
  src/common/types/NodeEndPoint.ts
  src/common/types/apiTypes.ts
  src/pages/flow-canvas/FlowCanvas.tsx
  src/pages/flow-canvas/components/custom-node/BodyEditor.tsx
  src/pages/flow-canvas/components/custom-node/CustomNode.tsx
  src/pages/flow-canvas/components/mock-api-modal/MockApiModal.tsx
  src/pages/flow-canvas/hooks/useCustomNode.ts
  src/pages/flow-canvas/hooks/useFlowCanvas.ts
  src/pages/flow-canvas/hooks/useMockApiModal.ts
  src/pages/flow-canvas/styles/ApiList.module.scss
  src/pages/flow-canvas/styles/CustomNode.module.scss
  src/pages/flow-canvas/styles/MappingModal.module.scss
  src/pages/flow-canvas/types/MockApiFormValues.ts
  src/pages/flow-canvas/types/index.ts
  src/styles/mixins/_httpMethod.scss
Labels: documentation, 0.0.1-BETA

#54 feat(flow-canvas): enable inline editing and auto default values for schema display
  src/common/types/NodeEndPoint.ts
  src/pages/flow-canvas/FlowCanvas.tsx
  src/pages/flow-canvas/__mocks__/mockNodeData.ts
  src/pages/flow-canvas/components/custom-node/BodyEditor.tsx
  src/pages/flow-canvas/controllers/BodyEditorTabsController.ts
  src/pages/flow-canvas/hooks/useBodyEditorController.ts
  src/pages/flow-canvas/hooks/useFlowCanvas.ts
  src/pages/flow-canvas/styles/BodyEditor.module.scss
  src/pages/flow-canvas/types/bodyEditor.ts
  src/pages/flow-canvas/types/index.ts
Labels: enhancement, 0.0.1-BETA

#64 feat(mock): implement mock API modal and JSON field parser
  src/common/utils/jsonUtils.ts
  src/common/utils/scenarioToReactFlow.ts
  src/pages/dashboard/Dashboard.tsx
  src/pages/dashboard/components/flow-graph-area/ApiRequestNode.tsx
  src/pages/dashboard/components/header-tabs/HeaderTabs.tsx
  src/pages/dashboard/components/table-area/DetailRow.tsx
  src/pages/dashboard/hooks/useScenarioFileList.ts
  src/pages/dashboard/styles/ApiRequestNode.module.scss
  src/pages/dashboard/styles/Dashboard.module.scss
  src/pages/dashboard/styles/FlowGraphArea.module.scss
  src/pages/dashboard/styles/HeaderTabs.module.scss
  src/pages/dashboard/styles/LatencyGraphArea.module.scss
  src/pages/dashboard/styles/MainContent.module.scss
  src/pages/dashboard/styles/TableArea.module.scss
  src/pages/dashboard/utils/rechartUtils.ts
  src/pages/flow-canvas/FlowCanvas.tsx
  src/pages/flow-canvas/components/custom-node/CustomEdge.tsx
  src/pages/flow-canvas/components/custom-node/CustomNode.tsx
  src/pages/flow-canvas/components/custom-node/EdgeLabelEditor.tsx
  src/pages/flow-canvas/components/custom-node/NodeBody.tsx
  src/pages/flow-canvas/components/custom-node/RenderJsonSchema.tsx
  src/pages/flow-canvas/components/mock-api-modal/MockApiModal.tsx
  src/pages/flow-canvas/hooks/useBodyEditor.ts
  src/pages/flow-canvas/hooks/useFlowCanvas.ts
  src/pages/flow-canvas/hooks/useMockApiModal.ts
  src/pages/flow-canvas/styles/BodyEditor.module.scss
  src/pages/flow-canvas/styles/CustomNode.module.scss
  src/pages/flow-canvas/styles/MockApiModal.module.scss
  src/store/thunks/exportScenario.ts
Labels: enhancement, 0.0.1-BETA

#65 feat(flow-canvas): Mapping Modal Mapping Work
  src/common/components/SaveButton.module.scss
  src/common/utils/schemaUtils.ts
  src/pages/flow-canvas/FlowCanvas.tsx
  src/pages/flow-canvas/FlowCanvasMain.tsx
  src/pages/flow-canvas/WelcomePage.tsx
  src/pages/flow-canvas/components/custom-node/CustomNode.tsx
  src/pages/flow-canvas/components/mapping-modal/MappingModal.tsx
  src/pages/flow-canvas/components/mapping-modal/MappingPanel.tsx
  src/pages/flow-canvas/components/scenario-list/ScenarioList.tsx
  src/pages/flow-canvas/hooks/useFlowCanvas.ts
  src/pages/flow-canvas/hooks/useMappingModal.ts
  src/pages/flow-canvas/hooks/useScenario.ts
  src/pages/flow-canvas/styles/FlowCanvasMain.module.scss
  src/pages/flow-canvas/styles/MappingModal.module.scss
  src/pages/flow-canvas/styles/WelcomePage.module.scss
  src/pages/flow-canvas/types/mapping.ts
  src/store/index.ts
  src/store/slices/flowSlice.ts
  src/store/slices/scenarioSlice.ts
  src/store/thunks/exportScenario.ts
Labels: enhancement, 0.0.1-BETA

#75 feat(flow-canvas): update icons, rename method, and fix export edge cases
  src/assets/icons/create.svg
  src/assets/icons/delete.svg
  src/assets/icons/fold.svg
  src/common/components/CommonSidebar.module.scss
  src/common/components/CommonSidebar.tsx
  src/common/components/PlayButton.tsx
  src/common/types/sidebarTypes.ts
  src/pages/flow-canvas/FlowCanvas.tsx
  src/pages/flow-canvas/FlowCanvasMain.tsx
  src/pages/flow-canvas/WelcomePage.tsx
  src/pages/flow-canvas/components/custom-node/CustomNode.tsx
  src/pages/flow-canvas/components/mapping-modal/MappingModal.tsx
  src/pages/flow-canvas/hooks/useFlowCanvas.ts
  src/pages/flow-canvas/hooks/useScenario.ts
  src/pages/flow-canvas/service/scenarioService.ts
  src/pages/flow-canvas/styles/ApiList.module.scss
  src/pages/flow-canvas/styles/FlowCanvasMain.module.scss
  src/pages/flow-canvas/styles/ScenarioList.module.scss
  src/pages/flow-canvas/types/scenarioTypes.ts
  src/store/slices/scenarioSlice.ts
  src/store/thunks/exportScenario.ts
Labels: enhancement, 0.0.1-BETA
